## SIB - P1

A Jupyter Notebook with examples of how to use the Dataset object.
26/09/2022

In [9]:
from si.data.dataset import Dataset
import numpy as np

# create a dataset
X = np.random.rand(150, 30)
y = np.random.randint(0, 2, 150)
dataset = Dataset(X, y)
dataset.shape()

(150, 30)

In [10]:
# get the X
dataset.X

array([[0.29937184, 0.29088345, 0.8745502 , ..., 0.22652198, 0.13422765,
        0.84920656],
       [0.89594306, 0.49564595, 0.5010191 , ..., 0.71892298, 0.0677103 ,
        0.39648797],
       [0.7647394 , 0.47330781, 0.92228641, ..., 0.99522226, 0.59584001,
        0.52370577],
       ...,
       [0.7669066 , 0.49119239, 0.56470705, ..., 0.85769364, 0.25500284,
        0.22049777],
       [0.05696413, 0.34402158, 0.24760902, ..., 0.3950474 , 0.71457077,
        0.15403229],
       [0.0988337 , 0.18255341, 0.94677667, ..., 0.48246431, 0.65026094,
        0.77748545]])

In [11]:
#get the features names
dataset.features

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29']

In [12]:
# has label?
dataset.has_label()

True

In [13]:
# print the label
dataset.y

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1])

In [14]:
# get classes
dataset.get_classes()

array([0, 1])

In [15]:
# statistics summary
dataset.summary()

0         1         2         3         4         5         6  \
mean    0.505224  0.495641  0.536674  0.518079  0.518573  0.494086  0.518956   
median  0.498092  0.488568  0.571538  0.516674  0.546892  0.468248  0.526553   
min     0.010516  0.033410  0.004882  0.006292  0.020139  0.001393  0.004775   
max     0.996122  0.985938  0.993056  0.994510  0.995710  0.977594  0.993907   
var     0.075040  0.074779  0.091779  0.087283  0.089546  0.095127  0.085902   

               7         8         9  ...        20        21        22  \
mean    0.507386  0.485507  0.463077  ...  0.538754  0.518713  0.488934   
median  0.521868  0.460990  0.427176  ...  0.557226  0.538943  0.478486   
min     0.003351  0.000849  0.003356  ...  0.001220  0.013229  0.000468   
max     0.997809  0.999508  0.991835  ...  0.989704  0.992530  0.991380   
var     0.086443  0.085082  0.082705  ...  0.090431  0.076967  0.086959   

              23        24        25        26        27        28        29  
mean    0.523220  0.532053  0.497382  0.463985  0.559446  0.474880  0.519276  
median  0.529158  0.534330  0.489653  0.451247  0.576764  0.467188  0.552788  
min     0.004382  0.003822  0.004570  0.001020  0.003724  0.022977  0.001064  
max     0.997086  0.995587  0.999501  0.998643  0.995222  0.992791  0.994163  
var     0.080430  0.091456  0.077541  0.086051  0.074166  0.076369  0.078641  

[5 rows x 30 columns]

In [4]:
from si.io.data_file import read_data_file

# read breast dataset from data file
breast_dataset = read_data_file('../datasets/breast-bin.data', sep=',', label=True)
breast_dataset.summary()

0          1          2          3          4          5  \
mean     4.417740   3.134478   3.207439   2.806867   3.216023   3.486409   
median   4.000000   1.000000   1.000000   1.000000   2.000000   1.000000   
min      1.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
max     10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
var      7.917053   9.298082   8.819630   8.141527   4.896110  13.099601   

                6          7          8  
mean     3.437768   2.866953   1.589413  
median   3.000000   1.000000   1.000000  
min      1.000000   1.000000   1.000000  
max     10.000000  10.000000  10.000000  
var      5.937114   9.311340   2.937284

In [5]:
breast_dataset.y

array([1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0.

In [6]:
print('Features', breast_dataset.features)
print('Label', breast_dataset.label)

Features ['0', '1', '2', '3', '4', '5', '6', '7', '8']
Label y


In [11]:
# write the same fila with a different name
from si.io.data_file import write_data_file
write_data_file('../datasets/breast-bin_tabular.tsv', breast_dataset, sep='\t', label=True)

In [7]:
from si.io.csv import read_csv

# read iris dataset from data file
iris_dataset = read_csv('../datasets/iris.csv', sep=',', features=True, label=True)
iris_dataset.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [8]:
iris_dataset.get_classes()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [10]:
# write the same file with a different name
from si.io.csv import write_csv
write_csv('../datasets/iris_tabular.tsv', iris_dataset, sep='\t', features=True, label=True)

In [13]:
# random dataset
from si.data.dataset import Dataset
random_dataset = Dataset.from_random(150, 30, 4)
random_dataset.get_classes()

array([0, 1, 2, 3])

In [16]:
# from dataframe
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(150, 30))
df_dataset = Dataset.from_dataframe(df)
df_dataset.X

array([[3.68692948e-01, 8.74545178e-01, 1.15637602e-01, ...,
        8.83831505e-01, 8.83505205e-01, 3.94059354e-01],
       [8.87478640e-01, 2.31762995e-01, 9.49997172e-01, ...,
        6.40969997e-01, 1.86734952e-01, 1.00128278e-01],
       [2.84061107e-02, 8.99152340e-01, 7.79864922e-01, ...,
        2.32829323e-01, 4.87284743e-04, 5.04144360e-01],
       ...,
       [7.84345223e-02, 4.93587035e-01, 8.21694429e-01, ...,
        8.28075353e-01, 6.01229380e-01, 1.04514501e-01],
       [1.48671278e-01, 2.21723869e-02, 4.87616386e-01, ...,
        6.81767357e-01, 8.69833128e-01, 4.82762773e-02],
       [6.05429247e-01, 6.17354467e-02, 8.15244932e-01, ...,
        1.36941954e-01, 4.93418147e-02, 2.26028206e-01]])

In [18]:
df_dataset.has_label()

False